classdef MCSSParser < handle
    % MCSSParser     A CSS Parser for MATLAB
    
    properties (Constant = true)
        tokens = struct(...
        'IDENT','{ident}',...
        'ATKEYWORD','@{ident}',...
        'STRING','{string}',...
        'BAD_STRING','{badstring}',...
        'BAD_URI','{baduri}',...
        'BAD_COMMENT','{badcomment}',...
        'HASH','#{name}',...
        'NUMBER','{num}',...
        'PERCENTAGE','{num}',...
        'DIMENSION','{num}{ident}',...
        'URI','url\({w}{string}{w}\)|url\({w}([!#$%&*-\[\]-~]|{nonascii}|{escape})*{w}\)',...
        'UNICODE- RANGE', 'u\+[0-9a-f?]{1,6}(-[0-9a-f]{1,6})?',...
        'CDO','<!--',...
        'CDC','-->',...
        ':', ':',...
        ';', ';',...
        '{', '\{',...
        '}', '\}',...
        '(', '\(',...
        ')', '\)',...
        '[', '\[',...
        ']', '\]',...
        'S', '[ \t\r\n\f]+',...
        'COMMENT', '\/\*[^*]*\*+([^/*][^*]*\*+)*\/',...
        'FUNCTION', '{ident}\(',...
        'INCLUDES', '~=',...
        'DASHMATCH', '|=');
    end
    
    methods
        function self = MCSSParser
        end
        
        function parseStyleSheet(self, src)
            
        end
    end
end